# Generated by Django 6.0.2 on 2026-04-06 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_genre_remove_anime_genre_remove_anime_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_type',
            field=models.CharField(choices=[('TV', 'Серіал'), ('MOVIE', 'Фільм'), ('OVA', 'OVA')], default='TV', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість серій'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="Ім'я")),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вік')),
                ('role', models.CharField(max_length=250, verbose_name='Роль')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/characters/', verbose_name='Фото')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='anime.anime', verbose_name='Аніме')),
                ('family', models.ManyToManyField(blank=True, to='anime.character', verbose_name='Родичі')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герої',
            },
        ),
    ]
