# Generated by Django 6.0.2 on 2026-04-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_type_anime_episodes_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
