# Generated by Django 6.0.2 on 2026-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_delete_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='movies_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість фільмів'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість серій'),
        ),
    ]
