# Generated by Django 6.0.5 on 2026-05-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_review_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
