# Generated by Django 6.0.5 on 2026-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='ova_count',
            field=models.IntegerField(default=0, verbose_name='Кількість OVA'),
        ),
    ]
