# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_ova_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Віковий рейтинг'),
        ),
        migrations.AddField(
            model_name='anime',
            name='related_anime',
            field=models.ManyToManyField(blank=True, to='anime.anime', verbose_name="Пов'язані тайтли"),
        ),
    ]
