# Generated by Django 6.0.5 on 2026-05-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_anime_age_rating_anime_related_anime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['title'], 'verbose_name': 'Аніме', 'verbose_name_plural': 'Аніме'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
    ]
