# Generated by Django 6.0.5 on 2026-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_anime_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
    ]
