# Generated by Django 5.2.11 on 2026-03-30 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0002_genre_remove_anime_genre_remove_anime_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Про себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('status_message', models.CharField(blank=True, max_length=100, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='anime.anime', verbose_name='Аніме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Дивлюсь'), ('completed', 'Переглянуто'), ('on_hold', 'Відкладено'), ('dropped', 'Кинуто'), ('planned', 'У планах')], default='planned', max_length=20, verbose_name='Статус')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Особистий рейтинг')),
                ('episodes_watched', models.PositiveSmallIntegerField(default=0, verbose_name='Переглянуто серій')),
                ('comment', models.TextField(blank=True, verbose_name='Мій коментар')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='anime.anime', verbose_name='Аніме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_anime_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список аніме користувача',
                'verbose_name_plural': 'Списки аніме користувачів',
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
