# Generated by Django 6.0.2 on 2026-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_delete_character'),
        ('profiles', '0003_review_rating_alter_review_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='anime.anime'),
        ),
    ]
