# Generated by Django 6.0.4 on 2026-04-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
