# Generated by Django 6.0.4 on 2026-04-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Нікнейм'),
        ),
    ]
