# Generated by Django 6.0.4 on 2026-05-16 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_review_parent'),
        ('profiles', '0006_profile_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranime',
            options={'verbose_name': 'Аніме у списку', 'verbose_name_plural': 'Списки аніме користувачів'},
        ),
        migrations.AlterUniqueTogether(
            name='useranime',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status_message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='episodes_watched',
            field=models.PositiveIntegerField(default=0, verbose_name='Переглянуто серій'),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(choices=[('WATCHING', 'Дивлюся'), ('WATCHED', 'Переглянуто'), ('PLANNING', 'У планах'), ('DROPPED', 'Кинуто')], default='PLANNING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='useranime',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='useranime',
            name='updated_at',
        ),
    ]
