# Generated by Django 6.0.5 on 2026-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_useranime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, default='Ми з України', max_length=100, verbose_name='Регіон'),
        ),
    ]
