# Generated by Django 6.0.5 on 2026-05-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Номер акаунту'),
        ),
    ]
