# Generated by Django 6.0.5 on 2026-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, default='Священні землі', max_length=100, verbose_name='Регіон'),
        ),
    ]
