# Generated by Django 5.2.11 on 2026-03-30 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='author',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='dubStudio',
        ),
        migrations.AddField(
            model_name='anime',
            name='authors',
            field=models.ManyToManyField(related_name='anime', to='anime.author', verbose_name='Автори'),
        ),
        migrations.AddField(
            model_name='anime',
            name='dub_studios',
            field=models.ManyToManyField(related_name='anime', to='anime.dubstudio', verbose_name='Студії дубляжу'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(upload_to='images/posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, verbose_name='Посилання на трейлер'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='dubstudio',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='dubstudio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва студії'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='anime.genre', verbose_name='Жанри'),
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
    ]
