# Generated by Django 5.2.11 on 2026-03-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0002_genre_remove_anime_genre_remove_anime_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="Ім'я")),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вік')),
                ('role', models.CharField(max_length=250, verbose_name='Роль')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/characters/', verbose_name='Фото')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='anime.anime', verbose_name='Аніме')),
                ('family', models.ManyToManyField(blank=True, to='characters.character', verbose_name='Родичі')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герої',
            },
        ),
    ]
