# Generated by Django 6.0.2 on 2026-04-06 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_type_anime_episodes_character'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_characters_list', to='anime.anime', verbose_name='Аніме'),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/characters/'),
        ),
    ]
