# Generated by Django 6.0.2 on 2026-04-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_movies_count_alter_anime_episodes'),
        ('characters', '0002_alter_character_anime_alter_character_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='anime.anime', verbose_name='Аніме'),
        ),
    ]
