# Generated by Django 6.0.4 on 2026-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День народження'),
        ),
    ]
