# Generated by Django 6.0.4 on 2026-04-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='family',
            field=models.ManyToManyField(blank=True, to='characters.character', verbose_name="Сім'я"),
        ),
    ]
